# Change these first
owner: AnimMouse # Your GitHub username
repo: animmouse-upptime # Your Github repository name

# Add your sites here
sites:
  - name: AnimMouse Main
    method: HEAD
    url: https://www.animmouse.com
  - name: AnimMouse Paraphrase
    method: HEAD
    url: https://paraphrase.animmouse.com
  - name: Atrack Tracker
    url: https://atrack.eu.org
  - name: Atrack Tracker News
    method: HEAD
    url: https://news.atrack.eu.org
  - name: 1 14 9 13
    method: HEAD
    url: https://www.114913.xyz
  - name: 1 14 9 13 redirects
    method: HEAD
    url: https://r.114913.xyz
  - name: Happy Tree Friends SWF
    method: HEAD
    url: https://happytreefriends.114913.xyz
  - name: Personal Site
    url: $PERSONAL_SITE
  - name: Mystical Rose Website
    method: HEAD
    url: https://www.mysticalroseschoolofcaloocan.com

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.animmouse.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: AnimMouse's Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a status page which uses **real-time** data from our [Github repository](https://github.com/AnimMouse/animmouse-upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration